"""updated some columns

Revision ID: 11e9e50aeb44
Revises: 
Create Date: 2025-02-10 15:49:27.447505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11e9e50aeb44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.drop_column('date_posted')
        batch_op.drop_column('category')
        batch_op.drop_column('apply_link')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('apply_link', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DATE(), nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('skills')

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
