"""added date posted column

Revision ID: 1b8a36c7c321
Revises: 11e9e50aeb44
Create Date: 2025-02-10 19:55:41.430090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8a36c7c321'
down_revision = '11e9e50aeb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
